# Create schemas

# Create tables
CREATE TABLE IF NOT EXISTS CLIENT
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOM_CLIENT VARCHAR(80),
    PRENOM_CLIENT VARCHAR(80),
    ADRESSE_CLEINT VARCHAR(200),
    CP_CLIENT VARCHAR(5),
    VILLE_CLIENT VARCHAR(100),
    TEL_CLIENT VARCHAR(15),
    MAIL_CLIENT VARCHAR(60),
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS TECHNICIEN
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOM_TECH VARCHAR(80),
    PRENOM_TECH VARCHAR(80),
    MDP_TECH VARCHAR(20),
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS PEC
(
    ID INT NOT NULL AUTO_INCREMENT,
    DATE_PEC DATE,
    ETAT_PEC VARCHAR(20),
    DESC_PEC VARCHAR(255),
    ID_CLIENT INT NOT NULL,
    ID_TECH INT NOT NULL,
    ID_MAT INT NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS MATERIEL
(
    ID INT NOT NULL AUTO_INCREMENT,
    MARQUE_MAT VARCHAR(30),
    NSERIE_MAT VARCHAR(30),
    TYPE_MAT VARCHAR(30),
    ID_CLIENT INT NOT NULL,
    PRIMARY KEY(ID)
);


# Create FKs
ALTER TABLE MATERIEL
    ADD    FOREIGN KEY (ID_CLIENT)
    REFERENCES CLIENT(ID)
;
    
ALTER TABLE PEC
    ADD    FOREIGN KEY (ID_CLIENT)
    REFERENCES CLIENT(ID)
;
    
ALTER TABLE PEC
    ADD    FOREIGN KEY (ID_TECH)
    REFERENCES TECHNICIEN(ID)
;
    
ALTER TABLE PEC
    ADD    FOREIGN KEY (ID_MAT)
    REFERENCES MATERIEL(ID)
;
    

# Create Indexes

